name: Update Pi-hole Blocklist

on:
  schedule:
    - cron: '0 4 * * *' # Täglich um 04:00 Uhr
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Verhindert, dass Node.js 20 Warnungen den Build stoppen
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests idna

      - name: Run Aggregator Script
        run: python main.py

      - name: Check for changes
        id: git-check
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Entferne die alte, zu große Datei aus dem Repo (ignoriert Fehler, falls sie schon weg ist)
          git rm -f pihole_blocklist.txt || true
          
          # Füge alle neu generierten Teil-Dateien hinzu
          git add pihole_blocklist_part*.txt
          
          # Prüft, ob es Änderungen gibt, um leere Commits zu vermeiden
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and Push
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git commit -m "Automatisches Update: $(date +'%Y-%m-%d %H:%M')"
          git push
